spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://185.223.93.175:5432/table
    username: postgres
    password: root58

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

bot:
  name: SelfServiceLaundryBot
  token: 7468172099:AAEJJJUQuhCQ0xWYaMh-V9NwbxWOQovqstg

parser:
  url: http://185.223.93.175:8091/
